### ISSUE TITLE
Crashes on CSV download

### ISSUE THREAD

**Issue by chriswhong** [NYCPlanning/deprecated-labs-zap-api#50]
App crashes on csv download... sometimes.  Need to troubleshoot and see if we can reproduce it.

Last logs before crash:
```

2018-07-22T16:26:14.517055858Z app[web.1]: GET /projects/tiles/r1CQg4GVX/8/75/96.mvt 204 70.175 ms - -
2018-07-22T16:26:24.438818678Z app[web.1]: internal/streams/legacy.js:59
2018-07-22T16:26:24.439446440Z app[web.1]:       throw er; // Unhandled stream error in pipe.
2018-07-22T16:26:24.439458589Z app[web.1]:       ^
2018-07-22T16:26:24.439464017Z app[web.1]: 
2018-07-22T16:26:24.439468752Z app[web.1]: Error: Data should not be empty or the "fields" option should be included
2018-07-22T16:26:24.439474110Z app[web.1]:     at Parser.parser.onToken (/app/node_modules/json2csv/dist/json2csv.cjs.js:4604:24)
2018-07-22T16:26:24.439479277Z app[web.1]:     at Parser.proto.write (/app/node_modules/json2csv/dist/json2csv.cjs.js:4225:34)
2018-07-22T16:26:24.439484195Z app[web.1]:     at JSON2CSVTransform._transform (/app/node_modules/json2csv/dist/json2csv.cjs.js:4642:19)
2018-07-22T16:26:24.439489124Z app[web.1]:     at JSON2CSVTransform.Transform._read (_stream_transform.js:186:10)
2018-07-22T16:26:24.439493870Z app[web.1]:     at JSON2CSVTransform.Transform._write (_stream_transform.js:174:12)
2018-07-22T16:26:24.439498637Z app[web.1]:     at doWrite (_stream_writable.js:387:12)
2018-07-22T16:26:24.439503214Z app[web.1]:     at writeOrBuffer (_stream_writable.js:373:5)
2018-07-22T16:26:24.439507889Z app[web.1]:     at JSON2CSVTransform.Writable.write (_stream_writable.js:290:11)
2018-07-22T16:26:24.439512568Z app[web.1]:     at Stream.ondata (internal/streams/legacy.js:16:26)
2018-07-22T16:26:24.439517369Z app[web.1]:     at emitOne (events.js:115:13)
2018-07-22T16:26:24.439521898Z app[web.1]:     at Stream.emit (events.js:210:7)
2018-07-22T16:26:24.439526716Z app[web.1]:     at drain (/app/node_modules/through/index.js:36:16)
2018-07-22T16:26:24.439531695Z app[web.1]:     at Stream.stream.queue.stream.push (/app/node_modules/through/index.js:45:5)
2018-07-22T16:26:24.439536620Z app[web.1]:     at Stream.<anonymous> (/app/node_modules/JSONStream/index.js:203:12)
2018-07-22T16:26:24.439541856Z app[web.1]:     at _end (/app/node_modules/through/index.js:65:9)
2018-07-22T16:26:24.439546585Z app[web.1]:     at Stream.stream.end (/app/node_modules/through/index.js:74:5)

```

**Comment by chriswhong** [comment]
Another log: 2018-07-24T21:34:26.462223275Z app[web.1]: internal/streams/legacy.js:59
2018-07-24T21:34:26.462256045Z app[web.1]:       throw er; // Unhandled stream error in pipe.
2018-07-24T21:34:26.462263380Z app[web.1]:       ^
2018-07-24T21:34:26.462268711Z app[web.1]: 
2018-07-24T21:34:26.462273465Z app[web.1]: Error: Data should not be empty or the "fields" option should be included
2018-07-24T21:34:26.462278990Z app[web.1]:     at Parser.parser.onToken (/app/node_modules/json2csv/dist/json2csv.cjs.js:4604:24)
2018-07-24T21:34:26.462283957Z app[web.1]:     at Parser.proto.write (/app/node_modules/json2csv/dist/json2csv.cjs.js:4225:34)
2018-07-24T21:34:26.462289007Z app[web.1]:     at JSON2CSVTransform._transform (/app/node_modules/json2csv/dist/json2csv.cjs.js:4642:19)
2018-07-24T21:34:26.462294079Z app[web.1]:     at JSON2CSVTransform.Transform._read (_stream_transform.js:186:10)
2018-07-24T21:34:26.462299049Z app[web.1]:     at JSON2CSVTransform.Transform._write (_stream_transform.js:174:12)
2018-07-24T21:34:26.462303925Z app[web.1]:     at doWrite (_stream_writable.js:387:12)
2018-07-24T21:34:26.462308710Z app[web.1]:     at writeOrBuffer (_stream_writable.js:373:5)
2018-07-24T21:34:26.462313555Z app[web.1]:     at JSON2CSVTransform.Writable.write (_stream_writable.js:290:11)
2018-07-24T21:34:26.462318579Z app[web.1]:     at Stream.ondata (internal/streams/legacy.js:16:26)
2018-07-24T21:34:26.462347379Z app[web.1]:     at emitOne (events.js:115:13)
2018-07-24T21:34:26.462353079Z app[web.1]:     at Stream.emit (events.js:210:7)
2018-07-24T21:34:26.462357854Z app[web.1]:     at drain (/app/node_modules/through/index.js:36:16)
2018-07-24T21:34:26.462362663Z app[web.1]:     at Stream.stream.queue.stream.push (/app/node_modules/through/index.js:45:5)
2018-07-24T21:34:26.462367493Z app[web.1]:     at Stream.<anonymous> (/app/node_modules/JSONStream/index.js:203:12)
2018-07-24T21:34:26.462372809Z app[web.1]:     at _end (/app/node_modules/through/index.js:65:9)
2018-07-24T21:34:26.462377638Z app[web.1]:     at Stream.stream.end (/app/node_modules/through/index.js:74:5)
2018-07-24T21:34:26.488496269Z app[web.1]: npm ERR! code ELIFECYCLE
2018-07-24T21:34:26.488626788Z app[web.1]: npm ERR! errno 1
2018-07-24T21:34:26.488747783Z app[web.1]: npm ERR! labs-lucats-proxy@1.0.0 start: `node ./bin/www`
2018-07-24T21:34:26.488825422Z app[web.1]: npm ERR! Exit status 1
2018-07-24T21:34:26.488898428Z app[web.1]: npm ERR! 
2018-07-24T21:34:26.489019195Z app[web.1]: npm ERR! Failed at the labs-lucats-proxy@1.0.0 start script.
2018-07-24T21:34:26.489143350Z app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2018-07-24T21:34:26.490391711Z app[web.1]: 
2018-07-24T21:34:26.490557576Z app[web.1]: npm ERR! A complete log of this run can be found in:
2018-07-24T21:34:26.490663181Z app[web.1]: npm ERR!     /app/.npm/_logs/2018-07-24T21_34_26_481Z-debug.log
2018-07-24T21:34:27.848433254Z app[web.1]: 
2018-07-24T21:34:27.848467389Z app[web.1]: > labs-lucats-proxy@1.0.0 start /app
2018-07-24T21:34:27.848473837Z app[web.1]: > node ./bin/www
2018-07-24T21:34:27.848478975Z app[web.1]: 
2018-07-24T21:34:28.721714663Z app[web.1]: ZAP API listening on port 5000

**Comment by chriswhong** [comment]
I suspect this is caused by triggering the download when there are 0 results in the filtered data.  Investigating...

**Comment by chriswhong** [comment]
Confirmed... ^^

**Comment by chriswhong** [comment]
Hotfixed in 8e02f99ea74e8a8af29cad5db4bb00cd450f967e.  I added a simple count query ahead of the stream, and only do the stream if count > 0.  It feels inefficient to call the database twice but I am not sure how to check handle a no data situation once the stream has already started.
